PG2024/Models/Producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DespachoProducto = new HashSet<DespachoProducto>();
            this.Inventario = new HashSet<Inventario>();
            this.TrasladoProducto = new HashSet<TrasladoProducto>();
        }
    
        public int ProductoID { get; set; }
        public string CodigoBarra { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> CategoriaID { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespachoProducto> DespachoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrasladoProducto> TrasladoProducto { get; set; }
    }
}

PG2024/Models/ViewModels/ProductoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PG2024.Models.ViewModels
{
    public class ProductoViewModel
    {

        [Required]
        [Display(Name = "CodigoBarra")]
        public string CodigoBarra { get; set; }
        [Required]
        [Display(Name = "Nombre del Producto")]
        public string Nombre { get; set; }
        [Required]
        [Display(Name = "Precio")]
        public decimal Precio { get; set; }
        [Required]
        [Display(Name = "CategoriaID")]
        public int CategoriaID { get; set; }

        [Display(Name = "Categoria")]
        public string NombreCategoria { get; set; }

    }


    public class EditProductoViewModel
    {
        public int ProductoID { get; set; }
        [Required]
        [Display(Name = "CodigoBarra")]
        public string CodigoBarra { get; set; }
        [Required]
        [Display(Name = "Nombre del Producto")]
        public string Nombre { get; set; }
        [Required]
        [Display(Name = "Precio")]
        public decimal Precio { get; set; }
        [Required]
        [Display(Name = "CategoriaID")]
        public int? CategoriaID { get; set; }

        [Display(Name = "Categoria")]
        public string NombreCategoria { get; set; }

    }
}

PG2024/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PG2024.Models;
using PG2024.Controllers;
using PG2024.Models.TablesNewModels;
using PG2024.Models.ViewModels;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;

namespace PG2024.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            List<ProductoTablaNewModel> lst = null;
            using (BoutiqueMEEntities db = new BoutiqueMEEntities())
            {
                lst = (from p in db.Producto
                       join c in db.Categoria on p.CategoriaID equals c.CategoriaID
                       select new ProductoTablaNewModel
                       {
                           ProductoID = p.ProductoID,
                           CodigoBarra = p.CodigoBarra,
                           Nombre = p.Nombre,
                           Precio = (decimal)p.Precio,
                           CategoriaID = (int)p.CategoriaID,
                           NombreCategoria = c.Nombre 
                       }).ToList();
            }
            return View(lst);
        }


        [HttpGet]
        public ActionResult Add()
        {
            
            ViewBag.Categorias = ObtenerCategorias();
            return View();
        }

        [HttpPost]
        public ActionResult Add(ProductoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categorias = ObtenerCategorias();
                return View(model);
            }

            using (var db = new BoutiqueMEEntities())
            {
                Producto producto = new Producto();
                producto.CodigoBarra = model.CodigoBarra;
                producto.Nombre = model.Nombre;
                producto.Precio = model.Precio;
                producto.CategoriaID = model.CategoriaID;

                db.Producto.Add(producto);
                db.SaveChanges();
            }

            return Redirect(Url.Content("~/Producto/"));
        }

        public ActionResult Edit(int ProductoID)
        {
            EditProductoViewModel model = new EditProductoViewModel();

            using (var db = new BoutiqueMEEntities())
            {
                var oUser = db.Producto.Find(ProductoID);

                model.CodigoBarra = oUser.CodigoBarra;
                model.Nombre = oUser.Nombre;
                model.Precio = (int)oUser.Precio;
                model.CategoriaID = oUser.CategoriaID;

                ViewBag.Categorias = ObtenerCategorias(); 
            }

            return View(model);
        }





        [HttpPost]
        public ActionResult Edit(EditProductoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new BoutiqueMEEntities())
            {
                var oUser = db.Producto.Find(model.ProductoID);
                oUser.CodigoBarra = model.CodigoBarra;
                oUser.Nombre = model.Nombre;
                oUser.Precio = model.Precio;
                oUser.CategoriaID = model.CategoriaID;
           

         
                db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }


            return Redirect(Url.Content("~/Producto/"));
             }





     
        [HttpPost]
        public ActionResult Delete(int ProductoID)
        {
            using (var db = new BoutiqueMEEntities())
            {
                try
                {
                    var producto = db.Producto.Find(ProductoID);
                    if (producto != null)
                    {
                        db.Producto.Remove(producto);
                        db.SaveChanges();
                    }
                    return Redirect(Url.Content("~/Producto/"));
                }
                catch (DbUpdateException ex)
                {
                    if (ex.InnerException is SqlException sqlEx && sqlEx.Message.Contains("FK__Inventari__Produ__2DE6D218"))
                    {
                        // Mostrar un mensaje de alerta al usuario
                        TempData["ErrorMessage"] = "No se puede eliminar el producto porque existen registros en el inventario que dependen de él.";
                    }
                    else
                    {
                        // Otro tipo de error, puedes manejarlo según tus necesidades
                        TempData["ErrorMessage"] = "Ocurrió un error al intentar eliminar el producto.";
                    }
                    return Redirect(Url.Content("~/Producto/"));
                }
            }
        }

        // Método privado para obtener las categorías disponibles
        private List<SelectListItem> ObtenerCategorias()
        {
            using (var db = new BoutiqueMEEntities())
            {
                return db.Categoria.Select(c => new SelectListItem
                {
                    Value = c.CategoriaID.ToString(),
                    Text = c.Nombre
                }).ToList();
            }
        }
    





}
}

PG2024/Views/Producto/Add.cshtml
@model PG2024.Models.ViewModels.ProductoViewModel
@{
    ViewBag.Title = "Agregar Producto";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Add", "Producto", FormMethod.Post, new { role = "form", @class = "" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationMessage("error", new { @class = "text-danger" })

            <!-- Codigo de Barras -->
            <div class="form-group">
                @Html.LabelFor(d => d.CodigoBarra)
                @Html.TextBoxFor(d => d.CodigoBarra, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.CodigoBarra, "", new { @class = "text-danger" })
            </div>

            <!-- Nombre del Producto -->
            <div class="form-group">
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, "", new { @class = "text-danger" })
            </div>

            <!-- Precio -->
            <div class="form-group">
                @Html.LabelFor(d => d.Precio)
                @Html.TextBoxFor(d => d.Precio, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Precio, "", new { @class = "text-danger" })
            </div>

            <!-- Categoría -->
            <div class="form-group">
                @Html.LabelFor(d => d.CategoriaID)
                @Html.DropDownListFor(d => d.CategoriaID, (IEnumerable<SelectListItem>)ViewBag.Categorias, "Seleccione una categoría", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.CategoriaID, "", new { @class = "text-danger" })
            </div>

            <div style="text-align: right">
                <input type="submit" class="btn btn-success" value="Crear" />
            </div>
        }
    </div>
</div>

PG2024/Views/Producto/Edit.cshtml
@model PG2024.Models.ViewModels.EditProductoViewModel
@{
    ViewBag.Title = "Editar Producto";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Edit", "Producto", FormMethod.Post, new { role = "form", @class = "" }))

        {

            @Html.HiddenFor(d => d.ProductoID)
            @Html.AntiForgeryToken()
            @Html.ValidationMessage("error", new { @class = "text-danger" })

            <!-- Codigo de Barras -->
            <div class="form-group">
                @Html.LabelFor(d => d.CodigoBarra)
                @Html.TextBoxFor(d => d.CodigoBarra, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.CodigoBarra, "", new { @class = "text-danger" })
            </div>

            <!-- Nombre del Producto -->
            <div class="form-group">
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, "", new { @class = "text-danger" })
            </div>

            <!-- Precio -->
            <div class="form-group">
                @Html.LabelFor(d => d.Precio)
                @Html.TextBoxFor(d => d.Precio, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Precio, "", new { @class = "text-danger" })
            </div>

            <!-- Categoría -->
            <div class="form-group">
                @Html.LabelFor(d => d.CategoriaID)
                @Html.DropDownListFor(d => d.CategoriaID, (IEnumerable<SelectListItem>)ViewBag.Categorias, "Seleccione una categoría", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.CategoriaID, "", new { @class = "text-danger" })
            </div>

            <div style="text-align: right">
                <input type="submit" class="btn btn-success" value="Guardar Cambios" />
            </div>
        }
    </div>
</div>

PG2024/Views/Producto/Index.cshtml
@model List<PG2024.Models.TablesNewModels.ProductoTablaNewModel>

@{
    ViewBag.Title = "Producto";
}

<h2>Productos</h2>
<div class="row">
    <div class="col-lg-12">
        <input type="button" class="btn btn-primary" onclick="document.location.href = '@Url.Content("~/Producto/Add")'" value="NUEVO PRODUCTO" />

    </div>

</div>
<br>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered">
            <tr>
                <th>Código de Barras</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Categoría</th>
                <th>Acciones</th>
            </tr>
            @foreach (var producto in Model)
            {
                <tr>
                    <td>@producto.CodigoBarra</td>
                    <td>@producto.Nombre</td>
                    <td>Q. @producto.Precio </td>
                    <td>@producto.NombreCategoria</td>
                    <td>
                        <div class="d-inline">
                            <form action="@Url.Action("Delete", "Producto")" method="post" onsubmit="return confirm('¿Estás seguro de que deseas eliminar este producto?');">
                                <input type="hidden" name="ProductoID" value="@producto.ProductoID" />
                                <input type="submit" value="Eliminar" class="btn btn-danger" />
                                <input onclick="document.location.href = '@Url.Action("Edit", "Producto", new { ProductoID = producto.ProductoID })'" type="button" value="Editar" class="btn btn-default" />
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </table>
        <input type="button" class="btn btn-default" onclick="document.location.href = '@Url.Content("~/Inventario")'" value="Volver" />
    </div>
</div>


@if (TempData["ErrorMessage"] != null)
{
    <script>alert("@TempData["ErrorMessage"]");</script>
}

<script>
    function jsDeleteConfirmation(ProductoID) {
        if (confirm("¿Estás seguro de que deseas eliminar este Producto?")) {
            var url = '@Url.Action("Delete", "Producto")' + '?ProductoID=' + ProductoID;
            // Realizar llamada AJAX para eliminar la categoría
            $.post(url, function(data) {
                if (data.success) {
                    // Si la eliminación es exitosa, redireccionar a la página Index y mostrar mensaje
                    window.location.href = '@Url.Action("~/Producto/")';
                } else {
                    // Si hay un error, mostrar mensaje de error
                    alert(data.errorMessage);
                }
            });
        }
        return false; // Evita que el formulario se envíe automáticamente
    }
</script>