PG2024/Controllers/CerrarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PG2024.Controllers
{
    public class CerrarController : Controller
    {
        public ActionResult Logoff()
        {

            Session["User"] = null;
            return RedirectToAction("Index", "Access");

        }
    }
}

PG2024/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PG2024.Models;
using PG2024.Controllers;
using PG2024.Models.TablesNewModels;
using PG2024.Models.ViewModels;

namespace PG2024.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            List<UserTableNewModel> lst = null;
            using (BoutiqueMEEntities db = new BoutiqueMEEntities())
            {
                lst = (from u in db.Usuario
                       join t in db.TipoUsuario on u.TipoUsuarioID equals t.TipoUsuarioID
                       join ti in db.Tienda on u.TiendaID equals ti.TiendaID
                       select new UserTableNewModel
                       {
                           UsuarioID = u.UsuarioID,
                           Nombre = u.Nombre,
                           TipoUsuarioID = u.TipoUsuarioID,
                           TipoUsuario = t.Tipo,
                           TiendaID = u.TiendaID,
                           NombreTienda = ti.Nombre
                       }).ToList();
            }

            return View(lst);
        }

        [HttpGet]
        public ActionResult Add()
        {

            return View();

        }
        [HttpPost]
        public ActionResult Add(UserViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);

            }

            using (var db = new BoutiqueMEEntities())
            {
                Usuario oUser = new Usuario();
                oUser.Nombre = model.Nombre;
                oUser.Contraseña = model.Contraseña;
                oUser.TipoUsuarioID = model.TipoUsuarioID;
                oUser.TiendaID = model.TiendaID;
                db.Usuario.Add(oUser);
                db.SaveChanges();
            }

            return Redirect(Url.Content("~/User/"));

        }



        public ActionResult Edit(int UsuarioID)
        {
            EditUserViewModel model = new EditUserViewModel();

            using (var db = new BoutiqueMEEntities())
            {
                var oUser = db.Usuario.Find(UsuarioID);

                model.Nombre = oUser.Nombre;
                model.TipoUsuarioID = (int)oUser.TipoUsuarioID;
                model.TiendaID = (int)oUser.TiendaID;
                model.UsuarioID = oUser.UsuarioID;





            }

            return View(model);
        }




        [HttpPost]
        public ActionResult Edit(EditUserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new BoutiqueMEEntities())
            {
                var oUser = db.Usuario.Find(model.UsuarioID);
                oUser.Nombre = model.Nombre;
                oUser.TipoUsuarioID = model.TipoUsuarioID;
                oUser.TiendaID = model.TiendaID;
                oUser.UsuarioID = model.UsuarioID;

                // Verifica si se proporcionó una nueva contraseña
                if (!string.IsNullOrEmpty(model.Contraseña))
                {
                    oUser.Contraseña = model.Contraseña;
                }

                db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }


            return Redirect(Url.Content("~/User/"));
        }



        [HttpPost]
        public ActionResult Delete(int UsuarioID)
        {
            using (var db = new BoutiqueMEEntities())
            {
                var oUser = db.Usuario.Find(UsuarioID);
                if (oUser != null)
                {
                    db.Usuario.Remove(oUser);
                    db.SaveChanges();
                }
            }

            return Redirect(Url.Content("~/User/"));
        }






    }
}

PG2024/Views/Shared/_LayoultCashier.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Boutique M. E</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CAJEROS", "Index", "Cashier", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Traslados", "Index", "User")</li>
                    <li>@Html.ActionLink("Crear venta", "Index", "Inventario")</li>

                    <li>@Html.ActionLink("Cerrar Sesión", "Logoff", "Cerrar")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PG2024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Boutique M. E</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Incluyendo el CDN de Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BOUTIQUE ME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "User")">
                            <i class="fas fa-users"></i> Usuarios
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Inventario")">
                            <i class="fas fa-truck"></i> Despacho
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Inventario")">
                            <i class="fas fa-cogs"></i> Administración
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Logoff", "Cerrar")">
                            <i class="fas fa-sign-out-alt"></i> Cerrar Sesión
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Boutique M. E</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PG2024/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BOUTIQUE ME</title>
    <link href="~/Content/css/IndexAccess.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>