PG2024/Models/Inventario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int InventarioID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public Nullable<int> TiendaID { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Tienda Tienda { get; set; }
    }
}

PG2024/Models/ViewModels/InventarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PG2024.Models.ViewModels
{
    public class InventarioViewModel
    {
       
 
        [Required]
        [Display(Name = "ProductoID")]
        public int ProductoID { get; set; }

        [Required]
        [Display(Name = "NombreProducto")]
        public string NombreProducto { get; set; }

        [Required]
        [Display(Name = "TiendaID")]
        public int TiendaID { get; set; }
        [Required]
        [Display(Name = "NombredeTienda")]
        public string NombreTienda { get; set; }
        [Required]
        [Display(Name = "Cantidad")]
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }



    }

    public class AddInventarioViewModel
    {


        [Required]
        [Display(Name = "Producto")]
        public int ProductoID { get; set; }
        public IEnumerable<SelectListItem> Productos { get; set; } = new List<SelectListItem>();


        [Required]
        [Display(Name = "Tienda")]
        public int TiendaID { get; set; }


        public IEnumerable<SelectListItem> Tiendas { get; set; } = new List<SelectListItem>();

        [Required]
        [Display(Name = "Cantidad")]
       
        public int Cantidad { get; set; }
    



    }



    public class EditInventarioViewModel
    {

        public int InventarioID { get; set; }
        [Required]
        [Display(Name = "ProductoID")]
        public int ProductoID { get; set; }
        
        [Required]
        [Display(Name = "TiendaID")]
        public int TiendaID { get; set; }
       
        [Required]
        [Display(Name = "Cantidad")]
        public int Cantidad { get; set; }
        public IEnumerable<SelectListItem> Productos { get; set; } = new List<SelectListItem>();
        public IEnumerable<SelectListItem> Tiendas { get; set; } = new List<SelectListItem>();


    }
}

PG2024/Controllers/InventarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PG2024.Models;
using PG2024.Controllers;
using PG2024.Models.TablesNewModels;
using PG2024.Models.ViewModels;

namespace PG2024.Controllers
{
   
    public class InventarioController : Controller
    {
       
        // GET: Inventario
        public ActionResult Index()
        {
            List<InventarioTableNewModel> inventario = new List<InventarioTableNewModel>();

            using (BoutiqueMEEntities db = new BoutiqueMEEntities())
            {
                inventario = (from inv in db.Inventario
                              join prod in db.Producto on inv.ProductoID equals prod.ProductoID
                              join tienda in db.Tienda on inv.TiendaID equals tienda.TiendaID
                              select new InventarioTableNewModel
                              {
                                  InventarioID = inv.InventarioID,
                                  ProductoID = (int)inv.ProductoID,
                                  NombreProducto = prod.Nombre,
                                  TiendaID = (int)inv.TiendaID,
                                  NombreTienda = tienda.Nombre,
                                  Cantidad = (int)inv.Cantidad,
                                  Precio = (decimal)prod.Precio

                              }).ToList();
            }

            return View(inventario);
        }


        [HttpGet]
        public ActionResult Add()
        {
            var model = new AddInventarioViewModel
            {
                Productos = GetProductos(), 
                Tiendas = GetTiendas()  
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(AddInventarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                
                using (var db = new BoutiqueMEEntities())
                {
                    Inventario inventario = new Inventario
                    {
                        ProductoID = model.ProductoID,
                        TiendaID = model.TiendaID,
                        Cantidad = model.Cantidad
                    };

                    db.Inventario.Add(inventario);
                    db.SaveChanges();
                }

                return Redirect(Url.Content("~/Inventario/"));
            }

           
            model.Productos = GetProductos();
            model.Tiendas = GetTiendas();

            return View(model);
        }

        public ActionResult Edit(int InventarioID)
        {
            EditInventarioViewModel model = new EditInventarioViewModel();

            using (var db = new BoutiqueMEEntities())
            {
                var oUser = db.Inventario.Find(InventarioID);

             
                model.ProductoID = (int)oUser.ProductoID;
                model.Productos = GetProductos();
                model.TiendaID =(int) oUser.TiendaID;
                model.Tiendas = GetTiendas();
                model.Cantidad = (int)oUser.Cantidad;
              

              
            }

            return View(model);
        }





        [HttpPost]
        public ActionResult Edit(EditInventarioViewModel model)
        {
            if (!ModelState.IsValid)
            {
            
                model.Productos = GetProductos();
                model.Tiendas = GetTiendas();
                return View(model);
            }

            using (var db = new BoutiqueMEEntities())
            {
                var oUser = db.Inventario.Find(model.InventarioID);
                oUser.ProductoID = model.ProductoID;
                oUser.TiendaID = model.TiendaID;
                oUser.Cantidad = model.Cantidad;
               



                db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }


            return Redirect(Url.Content("~/Inventario/"));
        }


        [HttpGet]
        public ActionResult AddUnits(int ProductoID, int TiendaID)
        {
            AddInventarioViewModel model = new AddInventarioViewModel
            {
                ProductoID = ProductoID,
                TiendaID = TiendaID,
                Productos = GetProductos(),
                Tiendas = GetTiendas(),
                Cantidad = 0 // Inicialmente vacío para que el usuario ingrese la cantidad
            };

            return View("AddUnits", model); // Reutilizamos la vista "Add" para aprovechar la estructura del formulario
        }

        [HttpPost]
        public ActionResult AddUnits(AddInventarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new BoutiqueMEEntities())
                {
                  
                    var inventarioExistente = db.Inventario
                        .FirstOrDefault(inv => inv.ProductoID == model.ProductoID && inv.TiendaID == model.TiendaID);

                    if (inventarioExistente != null)
                    {
                    
                        inventarioExistente.Cantidad += model.Cantidad;

                        db.Entry(inventarioExistente).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    else
                    {
                        ModelState.AddModelError("", "No se encontró el inventario para este producto y tienda.");
                    }
                }

                return Redirect(Url.Content("~/Inventario/"));
            }

          
            model.Productos = GetProductos();
            model.Tiendas = GetTiendas();

            return View("AddUnits", model);
        }





        [HttpPost]
        public ActionResult Delete(int InventarioID)
        {
            using (var db = new BoutiqueMEEntities())
            {
                var inventario = db.Inventario.Find(InventarioID);
                if (inventario != null)
                {
                    db.Inventario.Remove(inventario);
                    db.SaveChanges();
                }
            }

            return Redirect(Url.Content("~/Inventario/"));
        }





        private List<SelectListItem> GetProductos()
        {
            using (var db = new BoutiqueMEEntities())
            {
                return db.Producto.Select(p => new SelectListItem
                {
                    Value = p.ProductoID.ToString(),
                    Text = p.Nombre
                }).ToList();
            }
        }

        private List<SelectListItem> GetTiendas()
        {
            using (var db = new BoutiqueMEEntities())
            {
                return db.Tienda.Select(t => new SelectListItem
                {
                    Value = t.TiendaID.ToString(),
                    Text = t.Nombre
                }).ToList();
            }
        }
    }






   














    /*  [HttpGet]
      public ActionResult Add()
      {


          return View();

      }


      [HttpPost]
      public ActionResult Add(InventarioViewModel model)
      {
          if (!ModelState.IsValid)
          {

              return View(model);
          }

          using (var db = new BoutiqueMEEntities())
          {
              Inventario inventario  = new Inventario();
              inventario.ProductoID = model.ProductoID;
              inventario.TiendaID = model.TiendaID;
              inventario.Cantidad = model.Cantidad;


              db.Inventario.Add(inventario);
              db.SaveChanges();
          }

          return Redirect(Url.Content("~/Inventario/"));
      }*/
    /*
    public ActionResult Edit(int InventarioID)
        {
            EditInventarioViewModel model = new EditInventarioViewModel();

            using (var db = new BoutiqueMEEntities())
            {
                var oUser = db.Inventario.Find(InventarioID);

                model.ProductoID =(int) oUser.ProductoID;
                model.TiendaID = (int)oUser.TiendaID;
                model.Cantidad = (int)oUser.Cantidad;
              

            }

            return View(model);
        }




        [HttpPost]
        public ActionResult Edit(EditInventarioViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new BoutiqueMEEntities())
            {
                var oUser = db.Inventario.Find(model.InventarioID);
                oUser.ProductoID = model.ProductoID;
                oUser.TiendaID = model.TiendaID;
                oUser.Cantidad = model.Cantidad;



                db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }


            return Redirect(Url.Content("~/Inventario/"));
        }





       









       /* private List<SelectListItem> ObtenerProductos()
        {
            using (var db = new BoutiqueMEEntities())
            {
                var productos = db.Producto.Select(c => new SelectListItem
                {
                    Value = c.ProductoID.ToString(),
                    Text = c.Nombre
                }).ToList();

                return productos;
            }
        }

        // Método privado para obtener las categorías disponibles
        private List<SelectListItem> ObtenerTiendas()
        {
            using (var db = new BoutiqueMEEntities())
            {
                return db.Tienda.Select(c => new SelectListItem
                {
                    Value = c.TiendaID.ToString(),
                    Text = c.Nombre
                    
                    
                }).ToList();
            }
        }
       */











}

PG2024/Views/Inventario/Add.cshtml
@model PG2024.Models.ViewModels.AddInventarioViewModel

@{
    ViewBag.Title = "Agregar Inventario";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Add", "Inventario", FormMethod.Post, new { role = "form", @class = "" }))
        {
            <!-- Producto -->
            <div class="form-group">
                @Html.LabelFor(d => d.ProductoID)
                @Html.DropDownListFor(d => d.ProductoID, Model.Productos, "Seleccione un Producto", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.ProductoID, "", new { @class = "text-danger" })
            </div>

            <!-- Tienda -->
            <div class="form-group">
                @Html.LabelFor(d => d.TiendaID)
                @Html.DropDownListFor(d => d.TiendaID, Model.Tiendas, "Seleccione una Tienda", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.TiendaID, "", new { @class = "text-danger" })
            </div>

            <!-- Cantidad -->
            <div class="form-group">
                @Html.LabelFor(d => d.Cantidad)
                @Html.TextBoxFor(d => d.Cantidad, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Cantidad, "", new { @class = "text-danger" })
            </div>

            <div style="text-align: right">
                <input type="submit" class="btn btn-success" value="Crear" />
            </div>
        }
    </div>
</div>

PG2024/Views/Inventario/AddUnits.cshtml
@model PG2024.Models.ViewModels.AddInventarioViewModel

@{ ViewBag.Title = Model.Cantidad == 0 ? "Agregar Unidades" : "Agregar Inventario"; }

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm(Model.Cantidad == 0 ? "AddUnits" : "Add", "Inventario", FormMethod.Post, new { role = "form", @class = "" }))
        {
            <div>
                <div class="form-group">
                    @Html.LabelFor(d => d.ProductoID)
                    @Html.DropDownListFor(d => d.ProductoID, Model.Productos, new { @class = "form-control", @disabled = "disabled" })
                    @Html.HiddenFor(d => d.ProductoID)
                    @Html.ValidationMessageFor(d => d.ProductoID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(d => d.TiendaID)
                @Html.DropDownListFor(d => d.TiendaID, Model.Tiendas, new { @class = "form-control", @disabled = "disabled" })
                @Html.HiddenFor(d => d.TiendaID)
                @Html.ValidationMessageFor(d => d.TiendaID, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.Cantidad)
                @Html.TextBoxFor(d => d.Cantidad, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Cantidad, "", new { @class = "text-danger" })
            </div>

            <div style="text-align: right">
                <input type="submit" class="btn btn-success" value="@(Model.Cantidad == 0 ? "Agregar Unidades" : "Crear")" />
            </div>}
    </div>
</div>

PG2024/Views/Inventario/Edit.cshtml
@model PG2024.Models.ViewModels.EditInventarioViewModel

@{
    ViewBag.Title = "Editar Inventario";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Edit", "Inventario", FormMethod.Post, new { role = "form", @class = "" }))
        {
            @Html.HiddenFor(d => d.InventarioID)
            @Html.AntiForgeryToken()
            @Html.ValidationMessage("error", new { @class = "text-danger" })

            <!-- Producto -->
            <div class="form-group">
                @Html.LabelFor(d => d.ProductoID)
                @Html.DropDownListFor(d => d.ProductoID, Model.Productos, "Seleccione un Producto", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.ProductoID, "", new { @class = "text-danger" })
            </div>

            <!-- Tienda -->
            <div class="form-group">
                @Html.LabelFor(d => d.TiendaID)
                @Html.DropDownListFor(d => d.TiendaID, Model.Tiendas, "Seleccione una Tienda", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.TiendaID, "", new { @class = "text-danger" })
            </div>

            <!-- Cantidad -->
            <div class="form-group">
                @Html.LabelFor(d => d.Cantidad)
                @Html.TextBoxFor(d => d.Cantidad, new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Cantidad, "", new { @class = "text-danger" })
            </div>

            <div style="text-align: right">
                <input type="submit" class="btn btn-success" value="Guardar Cambios" />
            </div>
        }
    </div>
</div>

PG2024/Views/Inventario/Index.cshtml
@model List<PG2024.Models.TablesNewModels.InventarioTableNewModel>

@{
    ViewBag.Title = "Inventario";
}

<h2>Inventario</h2>
<div class="row">
    <div class="col-lg-12">
        <div style="margin-bottom: 10px;">
            <button class="btn btn-primary btn-sm" style="margin-right: 10px;" onclick="document.location.href = '@Url.Content("~/Producto/Index")'">Producto</button>
            <button class="btn btn-primary btn-sm" style="margin-right: 10px;" onclick="document.location.href = '@Url.Content("~/Categoria/Index")'">Categoria</button>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered">
            <tr>
                <th>Producto</th>
                <th>Tienda</th>
                <th>Cantidad</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.NombreProducto</td>
                    <td>@item.NombreTienda</td>
                    <td>@item.Cantidad</td>
                    <td>Q. @item.Precio</td>
                    <td>
                        <div class="btn-group" role="group">
                            <form action="@Url.Action("Delete", "Inventario")" method="post" onsubmit="return confirm('¿Estás seguro de que deseas eliminar este producto?');" style="display:inline;">
                                <input type="hidden" name="InventarioID" value="@item.InventarioID" />
                                <button type="submit" class="btn btn-danger btn-sm" style="margin-right: 10px;">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </form>

                            <button class="btn btn-primary btn-sm" style="margin-right: 10px;"
                                    onclick="document.location.href = '@Url.Action("AddUnits", "Inventario", new { ProductoID = item.ProductoID, TiendaID = item.TiendaID })'">
                                <i class="fas fa-plus"></i>
                            </button>

                            <button class="btn btn-default btn-sm" style="margin-right: 10px;"
                                    onclick="document.location.href = '@Url.Action("Edit", "Inventario", new { InventarioID = item.InventarioID })'">
                                <i class="fas fa-edit"></i>
                            </button>
                        </div>
                    </td>
                </tr>
            }
        </table>
        <button class="btn btn-primary btn-sm" onclick="document.location.href = '@Url.Content("~/Inventario/Add")'">
            <i class="fas fa-plus-circle"></i> Nuevo Registro
        </button>
    </div>
</div>

@if (TempData["ErrorMessage"] != null)
{
    <script>alert("@TempData["ErrorMessage"]");</script>
}

<script>
    function jsDeleteConfirmation(InventarioID) {
        if (confirm("¿Estás seguro de que deseas eliminar este Registro del Inventario?")) {
            var url = '@Url.Action("Delete", "Inventario")' + '?InventarioID=' + InventarioID;
            $.post(url, function(data) {
                if (data.success) {
                    window.location.href = '@Url.Action("~/Inventario/")';
                } else {
                    alert(data.errorMessage);
                }
            });
        }
        return false;
    }
</script>